### ISSUE TITLE
Add user profile image

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/communitypro.org#4]
If nominated, add your GitHub profile image to the `src/images` directory. 

- [ ] Profile One
- [ ] Profile Two
- [ ] Profile Three
- [ ] Profile Four

> **Note**
Tick the box when you make a successful pull request.

**Comment by Lil-Adonis** [comment]
If nominated ! 
i just joined the community not long and i have reviewed the src/images folder and i noticed images are yet to be added. Can i send a Pr ?

**Comment by Evavic44** [comment]
This issue is in anticipation of a feature we will like to have on the website. To avoid confusion, I'll be closing this for now. Thanks for joining the community. 🙂
