### ISSUE TITLE
Replace the hero paragraph text with communitypro bio

### ISSUE THREAD

**Issue by Evavic44** [CommunityPro/communitypro.org#5]
### Paraphrase this bio to a maximum of 30 words and then replace the lorem ipsum text in the hero section. 

> CommunityPro which stands for community project is a community of developers combining ideas to build open source projects and solutions. We believe developers learn more by teaching and building, which is the heart of this community and the reason we exist; To enhance the abilities of developers through teaching other developers and building open source projects with the knowledge.

**Comment by SincerelyBrittany** [comment]
Hi! Can I work on this issue?

**Comment by SincerelyBrittany** [comment]
Community Project ('CommunityPro') is a community of developers that build open source projects by combining ideas and creating solutions. We believe in learning by teaching and building as a community. (30 words)

Community Project ('CommunityPro') is a group of developers that believe in learning by teaching and building as a team. We build open source projects by combining ideas and creating solutions as a community. (33 words)

**Comment by Evavic44** [comment]
Hey, @SincerelyBrittany I've assigned this issue to you. But this issue depends on the hero section being added, so you can keep an eye out when we add it so you can raise a PR to fix this. Thanks.

**Comment by SincerelyBrittany** [comment]
Hi @Evavic44 has the hero section been added yet?

**Comment by Evavic44** [comment]
Not yet, @SincerelyBrittany ill tag you when it has. ⭐️
