### ISSUE TITLE
Add Community social links

### ISSUE THREAD

**Issue by Mannuel25** [CommunityPro/communitypro.org#7]
The social links of the community should be properly added. The URLs will be left below.

- [LinkedIn](https://www.linkedin.com/company/communitypro)
- [Discord](https://discord.gg/kn5sG8hqqc)
- [GitHub](https://github.com/CommunityPro)
- [Twitter](https://twitter.com/communitypro47)

**Comment by Pathholder1806** [comment]
Hey @Mannuel25 !
Can you elaborate where do you actually want the socials to be added ?

**Comment by abitsalihu** [comment]
Hey @Mannuel25  I would like to help on this issue. 🙂

**Comment by kenua** [comment]
Hi @Mannuel25 can I work on this issue?

**Comment by flexcommits** [comment]
Hi @Mannuel25 can I work on this issue?
